devmode: true
app:
  centryl:
    address: 127.0.0.1
    port: 9000
  api:
    address: 127.0.0.1
    port: 9002
  front:
    address: 127.0.0.1
    port: 9003

db:
  host: localhost
  port: 5432
  user: stilyan
  password: 'stil123'
  database: hyperion