name: demo

dependencies:
  intl: any
  cl:
    git: git@repo.centryl.org:centryl/cl.git
  cl_base:
    git: git@repo.centryl.org:centryl/cl_base.git
  worker:
    path: modules/worker
#  job:
#    path: modules/job

dev_dependencies:
  webdev: ^1.0.1
  build_runner: ^1.3.1
  build_web_compilers: ^1.2.0
#  cl_install:
#    git: git@repo.centryl.org:centryl/cl_install.git
